name: CI

on: [pull_request, push]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Spotless
        shell: bash
        run: |
          chmod +x ./gradlew
          ./gradlew spotlessApply
  build:
    name: "Build on ${{ matrix.os }} with Java ${{ matrix.jvm }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        jvm: ['11', '17']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm }}
      - name: Fix permissions
        if: ${{ matrix.os }} == "ubuntu" || ${{ matrix.os }} == "macos"
        run: |
          chmod +x ./gradlew
      - name: Build ShadowJar
        run: |
          ./gradlew shadowJar
      - name: Publish ShadowJar
        uses: actions/upload-artifact@v2
        with:
          name: grizzlytime-ci-jar
          path: build/libs/
